name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.x', 'master']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        check-latest: ${{ matrix.go == '1.x' }}

    - name: Install dependencies
      run: |
        go get github.com/mattn/goveralls
        go mod tidy

    - name: Test with coverage
      run: |
        go test -v -coverprofile=coverage.out ./...

    - name: Send coverage to Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out